oneup_flysystem:
    adapters:
        catalog_storage_adapter:
            local:
                location: '%kernel.project_dir%/var/file_storage/catalog'
        jobs_storage_adapter:
            local:
                location: '%kernel.project_dir%/var/file_storage/jobs'
        archivist_adapter:
            local:
                location: '%kernel.project_dir%/var/file_storage/archive'

        asset_storage_adapter:
            awss3v3:
                client: 'Aws\S3\S3Client'
                bucket: 'asset'
        data_quality_insights_shared_adapter:
            awss3v3:
                client: 'Aws\S3\S3Client'
                bucket: 'dataqualityinsights'
