/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BackendLabels =
  | {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` ".+".
       */
      [k: string]: string;
    }
  | [];

export interface BackendListAsset {
  identifier: string;
  code: string;
  labels: BackendLabels;
  image: BackendListValue[];
  asset_family_identifier: string;
  values:
    | {
        [k: string]: BackendListValue;
      }
    | [];
  completeness: BackendCompleteness;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` ".+".
 */
export interface BackendListValue {
  data: null | string | BackendMediaFile | string[];
  channel: string | null;
  locale: string | null;
  attribute: string;
}
export interface BackendMediaFile {
  filePath: string;
  originalFilename: string;
  size?: number;
  mimeType?: string;
  extension?: string;
  updatedAt?: string;
}
export interface BackendCompleteness {
  required: number;
  complete: number;
}
