/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BackendListValue {
  data: null | string | BackendMediaFile | string[];
  channel: string | null;
  locale: string | null;
  attribute: string;
}
export interface BackendMediaFile {
  filePath: string;
  originalFilename: string;
  size?: number;
  mimeType?: string;
  extension?: string;
  updatedAt?: string;
}
