parameters:
    installer_bundle.command.database_command.class: 'Akeneo\Platform\Bundle\InstallerBundle\Command\EnterpriseDatabaseCommand'
    pim_installer.install_status_manager.class: Akeneo\Platform\Bundle\InstallerBundle\InstallStatusManager\InstallStatusManager
services:
    Akeneo\Platform\Bundle\InstallerBundle\Command\CleanAttributeGroupAccessesCommand:
        arguments:
            - '@pimee_security.repository.attribute_group_access'
            - '@pim_user.repository.group'
        tags:
            - { name: 'console.command' }

    Akeneo\Platform\Bundle\InstallerBundle\Command\CleanCategoryAccessesCommand:
        arguments:
            - '@pimee_security.repository.category_access'
            - '@pim_user.repository.group'
            - '@doctrine.orm.default_entity_manager'
        tags:
            - { name: 'console.command' }

    pim_installer.install_status_manager:
        class: '%pim_installer.install_status_manager.class%'
        arguments:
            - '@doctrine'
            - '%env(APP_DATABASE_NAME)%'

    pim_installer.processor.denormalization.user:
        class: '%pim_connector.processor.denormalization.class%'
        arguments:
            - '@pim_user.repository.user'
            - '@pim_user.factory.user'
            - '@pim_user.updater.user'
            - '@validator'
            - '@akeneo_storage_utils.doctrine.object_detacher'
