/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BackendAssetFamilyNamingConvention {
  source?: {
    property: string;
    channel: string | null;
    locale: string | null;
    [k: string]: any;
  };
  pattern?: string;
  abort_asset_creation_on_error?: boolean;
  [k: string]: any;
}
