/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BackendAssetFamilyProductLinkRules = {
  product_selections?: {
    field: string;
    operator: string;
    value: (string | boolean | any[]) | string[];
    channel?: string | null;
    locale?: string | null;
    [k: string]: any;
  }[];
  assign_assets_to?: {
    attribute: string;
    mode: string;
    channel?: string | null;
    locale?: string | null;
    [k: string]: any;
  }[];
  [k: string]: any;
}[];
