/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BackendAssetFamilyTransformation = {
  label: string;
  source: {
    attribute: string;
    channel: string | null;
    locale: string | null;
  };
  target: {
    attribute: string;
    channel: string | null;
    locale: string | null;
  };
  operations: {
    type: string;
    parameters?: {
      [k: string]: any;
    };
    additionalProperties?: any;
    [k: string]: any;
  }[];
  filename_prefix?: string;
  filename_suffix?: string;
}[];
